version: '3'
services:
  db:
    image: mongo:4.4
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_DATABASE: nest-pokemon
    volumes:
      - ./mongo:/data/db


# version: '3'

# services:
#   db:
#     image: mongo:4.4
#     restart: always
#     ports:
#       - 27017:27017
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: admin
#       MONGO_INITDB_ROOT_PASSWORD: secret
#     volumes:
#       - ./mongo:/data/db
#       - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js      

# docker run -d \
#   --name mongo-container \
#   -p 27017:27017 \
#   -v $(pwd)/mongo-data:/data/db \
#   --restart=always \
#   mongo:5.0.0

